#!/bin/dash

output=$(tail -n6 ~/.config/dwlb/dwllogs)
active=$(echo "$output" | awk '/tags/ {print $3}')
selected=$(echo "$output" | awk '/tags/ {print $4}')
tags='0 1 2 3 4 5 6 7 8'

echo -n "   "
for tag in $tags; do
    mask=$((1<<tag))
    tagname=$((tag+1))
    echo -n "[$tagname]"
    [ $((active & mask)) -ne 0 ] && echo -n "~"
    [ $((selected & mask)) -ne 0 ] && echo -n "*"
    echo -n "   "
done
