#!/bin/dash

# The dash script for getting dwl tags' info, layout and title for two monitors.
# Replace eDP-1 and HDMI-A-1 with your monitors' names.

logs=$(tail -n 12 ~/.config/dwlb/dwllogs | grep "HDMI-A-1")

if [ -z $logs ]; then
    output6=$(tail -n 6 ~/.config/dwlb/dwllogs)
    active=$(echo "$output6" | awk '/eDP-1 tags/ {print $3}')
    selected=$(echo "$output6" | awk '/eDP-1 tags/ {print $4}')
    tags='0 1 2 3 4 5 6 7 8'

    echo -n "   "
    for tag in $tags; do
        mask=$((1<<tag))
        tagname=$((tag+1))
        echo -n "[$tagname]"
        [ $((active & mask)) -ne 0 ] && echo -n "~"
        [ $((selected & mask)) -ne 0 ] && echo -n "*"
        echo -n "   "
    done
else
    output12=$(tail -n 12 ~/.config/dwlb/dwllogs)
    active1=$(echo "$output12" | awk '/eDP-1 tags/ {print $3}')
    selected1=$(echo "$output12" | awk '/eDP-1 tags/ {print $4}')
    active2=$(echo "$output12" | awk '/HDMI-A-1 tags/ {print $3}')
    selected2=$(echo "$output12" | awk '/HDMI-A-1 tags/ {print $4}')

    tags='0 1 2 3 4 5 6 7 8'

    echo -n "   "

    for tag in $tags; do
        mask=$((1<<tag))
        tagname=$((tag+1))
        echo -n "eDP-1 --> "
        echo -n "[$tagname]"
        [ $((active1 & mask)) -ne 0 ] && echo -n "~"
        [ $((selected1 & mask)) -ne 0 ] && echo -n "*"
        echo "   "
        echo -n "HDMI-A-1 --> "
        echo -n "[$tagname]"
        [ $((active2 & mask)) -ne 0 ] && echo -n "~"
        [ $((selected2 & mask)) -ne 0 ] && echo -n "*"
        echo -n "   "
    done
fi
